[package]
name = "quoted_printable"
version = "0.2.0"
authors = ["Kartikaya Gupta <kats@seldon.staktrace.com>"]
description = "A simple encoder/decoder for quoted-printable data"
documentation = "https://staktrace.github.io/quoted-printable/target/doc/quoted_printable/"
homepage = "https://github.com/staktrace/quoted-printable/README.md"
repository = "https://github.com/staktrace/quoted-printable"
readme = "README.md"
keywords = ["decode", "encode", "quoted", "printable"]
license-file = "LICENSE"

[dependencies]
