[package]
name = "quoted_printable"
version = "0.1.1"
authors = ["Kartikaya Gupta <kats@seldon.staktrace.com>"]
description = "A simple decoder for quoted-printable input"
documentation = "https://staktrace.github.io/quoted-printable/quoted_printable/"
homepage = "https://github.com/staktrace/quoted-printable/README.md"
repository = "https://github.com/staktrace/quoted-printable"
readme = "README.md"
keywords = ["decode", "quoted", "printable"]
license-file = "LICENSE"

[dependencies]
